version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: weekly
    time: "05:00"
  open-pull-requests-limit: 10
  assignees:
  - JosephKav
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: weekly
    time: "05:00"
  open-pull-requests-limit: 10
  assignees:
  - JosephKav
